# Site settings
title: wanderweg.io
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  description of the website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wanderweg.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#Pagination settings
paginate: 2
paginate_path: "/blog/page:num/"
